@RivaRental.Web_HostAddress = http://localhost:5175

###
POST {{RivaRental.Web_HostAddress}}/rent/
Content-Type: application/json
{
    "BoatType":"IseoSuper"
}

###
POST {{RivaRental.Web_HostAddress}}/rent/
Content-Type: application/json
{
    "BoatType":"Diable"
}

###
GET https://localhost:7151/booking?Id=ba8106a6-fe17-4028-ba4b-4c91295ce2ca&BookingNumber=638795247090861767_Diable


###
POST {{RivaRental.Web_HostAddress}}/return/
Content-Type: application/json
{
    "BookingNumber": "Hello Rent!"
}

###
GET {{RivaRental.Web_HostAddress}}/booking/?BookingNumber=1
Accept: image/png